#!/usr/bin/env bash
# StormVPN all-in-one installer: platform (web, admin, API, database) + one WireGuard VPN node
# on a single fresh Ubuntu 22.04/24.04 or Debian 12 VPS (≥ 2 GB RAM, public IPv4).
#
#   curl -fsSL https://raw.githubusercontent.com/StormX1337/StormVPN/claude/vibrant-clarke-kuqenv/install.sh | sudo bash
#
# Optional settings (environment variables):
#   DOMAIN=vpn.example.com     own domain (A record → this server); default: <ip>.sslip.io
#   ADMIN_EMAIL=you@mail.com   first admin account; default: admin@<domain>
#   LE_EMAIL=you@mail.com      Let's Encrypt contact
#   SERVER_COUNTRY=DE SERVER_CITY=Nuremberg   location of this VPN node (default: detected)
#   SMTP_HOST SMTP_PORT SMTP_USER SMTP_PASSWORD SMTP_SECURE MAIL_FROM   real email delivery
#   STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET                            paid plans
#   SKIP_NODE=1                platform only (no VPN node on this host)
#   INSTALL_DIR=/opt/stormvpn  REPO_URL  BRANCH
# Safe to re-run (updates code, keeps .env, database and certificates).
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/stormvpn}"
REPO_URL="${REPO_URL:-https://github.com/StormX1337/StormVPN.git}"
BRANCH="${BRANCH:-claude/vibrant-clarke-kuqenv}"
CREDENTIALS_FILE=/root/stormvpn-credentials.txt

log() { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }
rand() { openssl rand -base64 "$1" | tr -d '\n'; }

[[ $EUID -eq 0 ]] || die "run as root (sudo bash install.sh)"
. /etc/os-release
[[ "$ID" == "ubuntu" || "$ID" == "debian" ]] || die "unsupported distribution: $ID (use Ubuntu 22.04/24.04 or Debian 12)"
export DEBIAN_FRONTEND=noninteractive

log "Installing base packages"
apt-get update -qq
apt-get install -y -qq ca-certificates curl git openssl certbot iproute2 >/dev/null

PUBLIC_IP="${PUBLIC_IP:-$(curl -fsS4 --max-time 10 https://api.ipify.org || true)}"
[[ "$PUBLIC_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "could not detect the public IPv4 – set PUBLIC_IP"
DOMAIN="${DOMAIN:-${PUBLIC_IP//./-}.sslip.io}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@${DOMAIN}}"
PUBLIC_URL="https://${DOMAIN}"

# Next.js builds need memory – add swap on small servers.
mem_mb=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)
if [[ $mem_mb -lt 3500 && -z "$(swapon --show)" ]]; then
  log "Adding 4 GB swap (RAM: ${mem_mb} MB)"
  fallocate -l 4G /swapfile && chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

if ! command -v docker >/dev/null; then
  log "Installing Docker"
  curl -fsSL https://get.docker.com | sh >/dev/null
fi
systemctl enable --now docker >/dev/null

log "Fetching StormVPN ($BRANCH) into $INSTALL_DIR"
if [[ -d "$INSTALL_DIR/.git" ]]; then
  git -C "$INSTALL_DIR" fetch -q origin "$BRANCH"
  git -C "$INSTALL_DIR" checkout -q "$BRANCH"
  git -C "$INSTALL_DIR" merge -q --ff-only "origin/$BRANCH"
else
  git clone -q --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

if [[ ! -f .env ]]; then
  log "Generating .env with random secrets"
  umask 077
  cat > .env <<ENV
NODE_ENV=production
LOG_LEVEL=info
LOG_PRETTY=false
PUBLIC_URL=${PUBLIC_URL}
HTTP_PORT=80
COOKIE_SECURE=true
POSTGRES_USER=stormvpn
POSTGRES_DB=stormvpn
POSTGRES_PASSWORD=$(openssl rand -hex 24)
JWT_ACCESS_SECRET=$(rand 48)
DATA_ENCRYPTION_KEY=$(rand 32)
METRICS_TOKEN=$(openssl rand -hex 24)
GRAFANA_ADMIN_PASSWORD=$(openssl rand -hex 12)
MAIL_FROM="${MAIL_FROM:-StormVPN <no-reply@${DOMAIN}>}"
ENV
  if [[ -n "${SMTP_HOST:-}" ]]; then
    cat >> .env <<ENV
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_SECURE=${SMTP_SECURE:-false}
SMTP_USER=${SMTP_USER:-}
SMTP_PASSWORD=${SMTP_PASSWORD:-}
REQUIRE_EMAIL_VERIFICATION=true
ENV
  else
    # Without a mail server users could never verify their address.
    echo "REQUIRE_EMAIL_VERIFICATION=false" >> .env
  fi
  if [[ -n "${STRIPE_SECRET_KEY:-}" ]]; then
    printf 'STRIPE_SECRET_KEY=%s\nSTRIPE_WEBHOOK_SECRET=%s\n' "$STRIPE_SECRET_KEY" "${STRIPE_WEBHOOK_SECRET:-}" >> .env
  fi
  umask 022
fi

log "Production configuration (HTTPS for $DOMAIN)"
install -d deploy/nginx /var/www/certbot
sed "s/stormvpn\.example/${DOMAIN}/g; s/ www\.${DOMAIN}//" infra/nginx/production/stormvpn.conf > deploy/nginx/stormvpn.conf
cat > docker-compose.override.yml <<'YAML'
# Generated by install.sh – production overrides (TLS, real SMTP).
x-smtp: &smtp
  SMTP_HOST: ${SMTP_HOST:-mailpit}
  SMTP_PORT: ${SMTP_PORT:-1025}
services:
  api:
    environment: *smtp
  worker:
    environment: *smtp
  scheduler:
    environment: *smtp
  nginx:
    ports: ['443:443']
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
YAML

if [[ ! -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]]; then
  log "Requesting a Let's Encrypt certificate (port 80 must be reachable)"
  docker compose stop nginx >/dev/null 2>&1 || true
  le_contact=(--register-unsafely-without-email)
  [[ -n "${LE_EMAIL:-}" ]] && le_contact=(-m "$LE_EMAIL")
  certbot certonly --standalone --non-interactive --agree-tos "${le_contact[@]}" -d "$DOMAIN" \
    --pre-hook "cd $INSTALL_DIR && docker compose stop nginx || true" \
    --post-hook "cd $INSTALL_DIR && docker compose start nginx || true" \
    || die "certificate request failed – is port 80 open and does $DOMAIN point to $PUBLIC_IP?"
fi

log "Building containers (first run takes 10–20 minutes)"
docker compose build
docker compose up -d

log "Waiting for the API"
api_id="$(docker compose ps -q api)"
for _ in $(seq 1 60); do
  [[ "$(docker inspect -f '{{.State.Health.Status}}' "$api_id" 2>/dev/null)" == "healthy" ]] && break
  sleep 5
done
[[ "$(docker inspect -f '{{.State.Health.Status}}' "$api_id")" == "healthy" ]] || die "API not healthy – docker compose logs api"

# Admin password is generated once and kept for re-runs.
if [[ -f "$CREDENTIALS_FILE" ]]; then
  ADMIN_PASSWORD="$(sed -n 's/^Admin password: //p' "$CREDENTIALS_FILE")"
fi
ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(openssl rand -base64 18 | tr -d '/+=')Aa1!}"

SERVER_COUNTRY="${SERVER_COUNTRY:-$(curl -fsS --max-time 5 https://ipinfo.io/country 2>/dev/null | tr -d '[:space:]' || true)}"
[[ "$SERVER_COUNTRY" =~ ^[A-Za-z]{2}$ ]] || SERVER_COUNTRY=DE
SERVER_CITY="${SERVER_CITY:-$(curl -fsS --max-time 5 https://ipinfo.io/city 2>/dev/null || true)}"
city_code="$(printf '%s' "$SERVER_CITY" | tr -cd '[:alpha:]' | tr '[:lower:]' '[:upper:]' | cut -c1-3)"
[[ ${#city_code} -ge 2 ]] || city_code=SRV
SERVER_NAME="${SERVER_NAME:-${SERVER_COUNTRY^^}-${city_code}-01}"

log "Creating plans, admin account and VPN server entry"
node_ip=""
[[ "${SKIP_NODE:-0}" == "1" ]] || node_ip="$PUBLIC_IP"
bootstrap_out="$(BOOTSTRAP_ADMIN_EMAIL="$ADMIN_EMAIL" BOOTSTRAP_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
  BOOTSTRAP_SERVER_IPV4="$node_ip" BOOTSTRAP_SERVER_NAME="$SERVER_NAME" BOOTSTRAP_SERVER_HOSTNAME="$DOMAIN" \
  BOOTSTRAP_SERVER_COUNTRY="$SERVER_COUNTRY" BOOTSTRAP_SERVER_CITY="$SERVER_CITY" \
  docker compose run --rm -T -e BOOTSTRAP_ADMIN_EMAIL -e BOOTSTRAP_ADMIN_PASSWORD -e BOOTSTRAP_SERVER_IPV4 \
  -e BOOTSTRAP_SERVER_NAME -e BOOTSTRAP_SERVER_HOSTNAME -e BOOTSTRAP_SERVER_COUNTRY -e BOOTSTRAP_SERVER_CITY \
  migrate pnpm run --silent bootstrap)"
grep -v '^ENROLLMENT_TOKEN=' <<<"$bootstrap_out" || true
ENROLLMENT_TOKEN="$(sed -n 's/^ENROLLMENT_TOKEN=//p' <<<"$bootstrap_out")"

umask 077
cat > "$CREDENTIALS_FILE" <<CRED
StormVPN
Website:        ${PUBLIC_URL}
Admin panel:    ${PUBLIC_URL}/admin
Admin email:    ${ADMIN_EMAIL}
Admin password: ${ADMIN_PASSWORD}
CRED
umask 022

if [[ "${SKIP_NODE:-0}" != "1" ]]; then
  log "Building the node agent"
  docker build -q -f infra/docker/node-agent.Dockerfile --target builder -t stormvpn/agent-builder:local . >/dev/null
  cid="$(docker create stormvpn/agent-builder:local)"
  install -d dist
  docker cp "$cid:/repo/services/node-agent/dist/stormvpn-agent.mjs" dist/stormvpn-agent.mjs >/dev/null
  docker rm "$cid" >/dev/null

  log "Installing the WireGuard VPN node ($SERVER_NAME)"
  STORMVPN_API_URL="$PUBLIC_URL" STORMVPN_ENROLLMENT_TOKEN="$ENROLLMENT_TOKEN" \
    AGENT_BUNDLE="$INSTALL_DIR/dist/stormvpn-agent.mjs" bash infra/wireguard/install-node.sh
fi

curl -fsS --max-time 10 "$PUBLIC_URL/health/ready" >/dev/null || echo "Warning: $PUBLIC_URL/health/ready not reachable yet"

printf '\n\033[1;32m✔ StormVPN is installed\033[0m\n\n'
cat "$CREDENTIALS_FILE"
cat <<INFO

Credentials saved in ${CREDENTIALS_FILE} (root only).
Open ports in your provider firewall: TCP 80, TCP 443, UDP 51820.
Logs: cd ${INSTALL_DIR} && docker compose logs -f api · journalctl -u stormvpn-agent -f
INFO
