packages:
  - "apps/*"
  - "services/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "@node-rs/argon2"
  - "msgpackr-extract"
  - "sharp"
  - "unrs-resolver"
